### ISSUE TITLE
Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by guiguan** [prisma-labs/vscode-graphql#75]
VSCode version: 1.27.2
Extension version: 0.1.5

Got this error when using this extension:

```
  ERR Cannot read property 'kind' of undefined: TypeError: Cannot read property 'kind' of undefined
	at asHoverContent (/Users/guiguan/.vscode/extensions/prisma.vscode-graphql-0.1.5/node_modules/vscode-languageclient/lib/protocolConverter.js:101:27)
	at asHover (/Users/guiguan/.vscode/extensions/prisma.vscode-graphql-0.1.5/node_modules/vscode-languageclient/lib/protocolConverter.js:134:31)
	at propagateAslWrapper (/Users/guiguan/.vscode/extensions/vscjava.vscode-maven-0.11.0/node_modules/async-listener/index.js:502:23)
	at /Users/guiguan/.vscode/extensions/vscjava.vscode-maven-0.11.0/node_modules/async-listener/glue.js:188:31
	at /Users/guiguan/.vscode/extensions/vscjava.vscode-maven-0.11.0/node_modules/async-listener/index.js:539:70
	at /Users/guiguan/.vscode/extensions/vscjava.vscode-maven-0.11.0/node_modules/async-listener/glue.js:188:31
	at <anonymous>
```

**Comment by 5achinJani** [comment]
I'm having the exact same issue and same error in the logs.
```
[2019-03-26 19:28:00.467] [exthost] [error] [Prisma.vscode-graphql] provider FAILED
[2019-03-26 19:28:00.467] [exthost] [error] TypeError: Cannot read property 'kind' of undefined
	at asHoverContent (/Users/sachin.jani/.vscode/extensions/prisma.vscode-graphql-0.1.7/node_modules/vscode-languageclient/lib/protocolConverter.js:101:27)
	at asHover (/Users/sachin.jani/.vscode/extensions/prisma.vscode-graphql-0.1.7/node_modules/vscode-languageclient/lib/protocolConverter.js:134:31)
```
`.graphqlconfig.yml`
```
projects:
  app:
    schemaPath: src/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://localhost:4000
  db:
    schemaPath: src/generated/prisma-client/prisma.graphql
```
-  src/schema.graphql `exists` - checked.
- src/generated/prisma-client/prisma.graphql `exists` - checked.
- Extension version 0.1.7
- VSCode version 1.32
- System : Mac
- System node version set using nvm : v10.0.0

I'm not getting IntelliSense, definition snippet on hover, and autocomplete.
