### ISSUE TITLE
IntelliSense/hover, Go to Definition, Peek Definition all broken

### ISSUE THREAD

**Issue by peterschussheim** [prisma-labs/vscode-graphql#87]
## Actual Behavior

It appears that syntax highlighting works properly.  Otherwise, the features mentioned in title do not work.

## Specifications

  - GraphQL for VSCode Extension Version: 0.1.6
  - VSCode Version: Version 1.29.0-insider (1.29.0-insider)
  - OS Name: macos
  - OS Version: 10.14 (18A391)

**Comment by deftomat** [comment]
Maybe similar to https://github.com/prisma/vscode-graphql/issues/84

**Comment by alexlafroscia** [comment]
I'm having the same issue, I think.

I have a `.graphqlconfig` file in the root of my project, but auto-complete in my `.graphql` files is just based on words in the current file, not based on the actual GraphQL schema.

Looking at the output from the GraphQL Language Server in the **Output** tab, there's just nothing at all reported.

**Comment by WDFS** [comment]
Same problem here. every functionalities except the syntax highlighting aren't working at all.

**Comment by alexlafroscia** [comment]
I was finally able to get this to work... I'm not sure exactly what changed, but I added the `includes` field to my `.graphqlconfig` file to specify which files should use which schema (I have multiple projects in this repo). While I used to not get any of the feedback I was expecting, things seem to be working now.

**Comment by divyenduz** [comment]
@alexlafroscia As the [documentation suggests](https://github.com/prisma/vscode-graphql#usage), adding files to includes is the intended way to use this extension. 

For others, please share a minimal project that I can use to reproduce this issues? Once the `.graphqlconfig` is provided, the language features of the extension should kick in.

**Comment by steida** [comment]
@divyenduz I tried it again and no matter what I set it only do highlight. You can check it here: https://github.com/este/este

**Comment by kotojo** [comment]
Also having this issue. I've tried two setups to my config file with no avail.
```
projects:
  api:
    schemaPath: ./packages/graphql/src/schema/schema.graphql
    includes: ["**/*.graphql"]
  venue:
    schemaPath: ./packages/graphql/src/schema/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://development.gatherhere.com:5000/graphql
```

and just no projects like this

```
    schemaPath: ./packages/graphql/src/schema/schema.graphql
    includes: ["**/*.graphql"]
    extensions:
      endpoints:
        default: http://development.gatherhere.com:5000/graphql
```

Either way I get typeahead for my queries, but writing any new types server side results in nothing but syntax highlighting. No matter what I cannot get go to definition to do anything though. Also I have no errors or output of any sort from GraphQL Language Server.

**Comment by switz** [comment]
I'm not getting any intellisense in any queries (inline gql or `.graphql` files):
```
projects:
  admin:
    schemaPath: ./packages/admin/schema.graphql
    includes: ["./packages/admin/**/*.{ts,tsx,graphql}"]
    extensions:
      endpoints:
        dev:
          url: "http://XXXXXXX.com/v1/graphql"
          headers:
            x-hasura-admin-secret: XXXXXXXX
```

But executing the queries works great.
